const FilteringActionType = {
	CHANGE_SEARCH_FIELD:'CHANGE_SEARCH_FIELD',
	TOGGLE_SEARCH_BAR_HIDDEN:'TOGGLE_SEARCH_BAR_HIDDEN',
	NEXT_PAGE:'NEXT_PAGE',
	PREVIOUS_PAGE:'PREVIOUS_PAGE'
}

export default FilteringActionType;