const shopActionType = {
	ADD_ELABORATED_ITEM: 'ADD_ELABORATED_ITEM',
	GET_ELABORATED_ITEM: 'GET_ELABORATED_ITEM',
	REMOVE_ELABORATED_ITEM: 'REMOVE_ELABORATED_ITEM',
	FETCH_COLLECTIONS_START: 'FETCH_COLLECTIONS_START',
	FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
	FETCH_COLLECTIONS_FAILURE: 'FETCH_COLLECTIoNs_FAILURE'
}

export default shopActionType;